---

_: &offsite_gpg_key '13B84C37AB52D76B3F53CF0E7C34BD7A05119BA4'
_: &offsite_host 'backup0.backup.provider0.production.govuk.service.gov.uk'
_: &offsite_ssh_host_key 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDJb4hocHMvkgk5ebOl7fzzNmgJb4N3LbGc3dm8Grvmx9QTnyG3nWyF1g0j69IvOAIhhZZd62ntzXN8a3PaPhxVPG6rA8D5LHSBBhXC1cwiG9FYKccdwYruNit8OgPuXmsCqXKleW6bqIgARDdj5iVDo1HNkWl05r1vH+RWjZFAB6p4D1RoTFCvbu8OI0nybS1rx2w+zZmCof92w8RcgYt2oaX9+n2enP7aL76Bg88pkElJvDSg8UQ61Dm9hVRb15KBAw0GsfydIRk2SY3SJsn5lRjrUPSmSPfb2VPpprYLNcf3wvINi0zW2Nv0pqnY5jRaHfFvpfgajQznxMDD18u1'

app_domain: 'publishing.service.gov.uk'

asset_root: 'https://assets-origin.publishing.service.gov.uk'

backup::assets::dest_host: *offsite_host
backup::assets::dest_host_key: *offsite_ssh_host_key
backup::assets::jobs:
  'assets-whitehall':
    sources: '/mnt/uploads/whitehall'
    destination: "rsync://govuk-assets@%{hiera('backup::assets::dest_host')}//srv/backup-assets/whitehall"
    hour: 4
    minute: 20
    user: 'root'
    gpg_key_id: *offsite_gpg_key
  'asset-manager':
    sources: '/mnt/uploads/asset-manager'
    destination: "rsync://govuk-assets@%{hiera('backup::assets::dest_host')}//srv/backup-assets/asset-manager"
    hour: 4
    minute: 13
    user: 'root'
    gpg_key_id: *offsite_gpg_key

backup::offsite::dest_host: *offsite_host
backup::offsite::dest_host_key: *offsite_ssh_host_key
backup::offsite::jobs:
  'govuk-datastores':
    sources:
      - '/data/backups/*/var/lib/automongodbbackup/latest'
      - '/data/backups/*/var/lib/automysqlbackup/latest.tbz2'
      - '/data/backups/*/var/lib/autopostgresqlbackup/latest.tbz2'
      - '/data/backups/archived'
    destination: "rsync://%{hiera('backup::offsite::dest_host')}//srv/backup-data/"
    hour: 8,
    minute: 13,
    gpg_key_id: *offsite_gpg_key
  'govuk-graphite':
    sources: '/data/backups/*/opt/graphite/storage/whisper'
    destination: "rsync://%{hiera('backup::offsite::dest_host')}//srv/backup-graphite/"
    weekday: 6
    hour: 8,
    minute: 13,
    # No encryption because of size and sensitivity
backup::offsite::monitoring::offsite_fqdn: *offsite_host
backup::offsite::monitoring::offsite_hostname: 'backup0.provider0'

internal_tld: 'publishing.service.gov.uk'

shell::shell_prompt_string: 'migration-production'

govuk_bouncer::gor::enabled: true
govuk_bouncer::gor::ip_address: '31.210.245.69'

# FIXME: Remove once these are disabled in Skyscape Production
govuk_crawler::seed_enable: false
govuk_crawler::sync_enable: false
# END FIXME

govuk::apps::content_register::db::backend_ip_range: '10.3.3.0/24'

govuk::apps::email_alert_api::db::backend_ip_range: '10.3.3.0/24'
govuk::apps::email_alert_monitor::db::backend_ip_range: '10.3.3.0/24'

govuk::apps::errbit::errbit_email_from: 'govuk-winston+errbit-production-migration@digital.cabinet-office.gov.uk'

# FIXME: Remove this line during migration to Carrenza
govuk::deploy::actionmailer_enable_delivery: false

govuk::deploy::setup::ssh_keys:
  jenkins_production_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDvfe5R+1OKwEBQqQIECW4k4LaFrTZedFWK5pzSAM6QxpQtCbKau4ZnD1ToPLX/IGYnW9m/2QfTQoBUtJvERjJvvGs7Wy6I+nKpr4gBVuDiFWilaXZ0rhdlnfU+r/DvFwRR5qjt7pewAlzdcDKp/NAa9BPIYL+YSX4XAZE0b8YMGxeJFQ4sd4CloTJxiUF2F1t2OObXhdQfp2BKtjHMwqClxW6ZthjKcqT4tBkZfo/gzd0TG0FmykNH+tG5q9Y7oxxe52TfJudIobSLgbmXOoEuSNjlwgktb6B+K3J08txo7dG0HrDdamSDTQxXVhn1K1re3cMJokV0N59hazHh7+vx'
  jenkins_skyscape_production_key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDZ41opiEUbMk1N3wNQLrsA3bwDWlf77mGiZAUyv8rDqwwUyRgdjXBIl8+/UUUromm3XzWXgeMiQkPSZMXu2U06X05BgW90Hl8lXsL24K0JRjLf6R7erMvqjpr0u5BTRxeKVSM52ckSUiucJHBiV5gTNRTUSwwXudjnlIY5HZRYNUUUtQMwfMObg6W3j+H/87gDx5RAF4JfOplK+pvHh0uGhIUrq48Euz2KJ31YsyO4FyU6z4k66MtJivkbZ/4Z9BpzzONnL1EC5saz7vaJIRGc0kT9NVGQ7b7uMkqlN/Bb/ZDzNJi8KSxJFTh8oNEAoRoMqaSufBlZa/sjqiuWniwL'

govuk::apps::policy_publisher::db::backend_ip_range: '10.3.3.0/24'
govuk::apps::publishing_api::db::backend_ip_range: '10.3.3.0/24'
govuk::apps::stagecraft::postgresql_db::api_ip_range: '10.3.4.0/24'
govuk::apps::support_api::db::backend_ip_range: '10.3.3.0/24'
govuk::apps::transition::postgresql_db::backend_ip_range: '10.3.3.0/24'
govuk::apps::url_arbiter::db::backend_ip_range: '10.3.3.0/24'

govuk::node::s_api_redis::allowed_ip_range: '10.3.4.0/24'

govuk::node::s_asset_base::firewall_allowed_ip_range: '10.3.3.0/24'

govuk::node::s_backup::backup_efg: false
govuk::node::s_backup::backup_licensify: false

govuk::node::s_transition_postgresql_slave::redirector_ip_range: '10.3.5.0/24'

govuk_jenkins::job::smokey::build_branch: 'smokey-failure-licensing'

grafana::dashboards::machine_suffix_metrics: ''

hosts::production::apt_mirror_internal: false
hosts::production::efg_domains: []

# FIXME: Set to true as part of Production migration; workaround to prevent
# traffic replay from hitting Licensify in Skyscape Production.
# See: https://docs.google.com/document/d/1lsfmEsL8maY77Yf2a-hq1c7P-8oF5PC4MTy59uOxDRI
hosts::production::external_licensify: false

hosts::production::licensify_hosts:
  licensify.production.alphagov.co.uk:
    ip: '37.26.90.230'
  licensify-admin.production.alphagov.co.uk:
    ip: '37.26.90.233'
hosts::production::management::apt_host_ip: '10.3.0.75'

website_root: 'https://www-origin.publishing.service.gov.uk'

govuk_jenkins::config::banner_colour_background: '#ff3300'
govuk_jenkins::config::banner_colour_text: 'white'
govuk_jenkins::config::banner_string: 'Carrenza PRODUCTION'

govuk_jenkins::config::manage_config: true

govuk_jenkins::config::admins:
  - alexmuller
  - andrewlanghorn
  - bobwalker
  - ci_alphagov
  - joshmyers
  - mattbostock
  - paulmartin

govuk_jenkins::config::users:
  - aaronkeogh
  - alexmuller
  - alextomlins
  - andrewlanghorn
  - bobwalker
  - bradleywright
  - danielroseman
  - davidheath
  - davidsingleton
  - deploy
  - eddsowden
  - elliotcrosbymccullough
  - jacobashdown
  - jakebenilov
  - jamiecobbett
  - jennyduckett
  - joshmyers
  - kushalpisavadia
  - mattbostock
  - paulmartin
  - richardboulton
  - robyoung
  - timothymower
  - tombooth
  - tommypalmer

govuk_jenkins::job_builder::manage_jobs: true
# FIXME: The data_sync_complete job is only in this list during migration to Carrenza
#        because Carrenza Production is being treated as a Staging environment.
govuk_jenkins::job_builder::jobs:
  - govuk_jenkins::job::staging::data_sync_complete
  - govuk_jenkins::job::production::build_offsite_backup
  - govuk_jenkins::job::production::check_cdn_ip_ranges
  - govuk_jenkins::job::production::ci_network_config
  - govuk_jenkins::job::production::copy_data_to_preview
  - govuk_jenkins::job::production::copy_data_to_staging
  - govuk_jenkins::job::production::gds_production_backup
  - govuk_jenkins::job::production::mirror_network_config
  - govuk_jenkins::job::production::production_redirector_cdn
  - govuk_jenkins::job::production::run_govuk_complaint_rate_report
  - govuk_jenkins::job::production::search_fetch_analytics_data
  - govuk_jenkins::job::production::trade_tariff_reindex_elasticsearch
  - govuk_jenkins::job::production::transition_load_all_data
  - govuk_jenkins::job::production::transition_load_site_config
  - govuk_jenkins::job::production::transition_load_transition_stats_hits
  - govuk_jenkins::job::production::whitehall_rebuild_elasticsearch_index
  - govuk_jenkins::job::production::whitehall_run_broken_link_checker
  - govuk_jenkins::job::deploy_router_data
  - govuk_jenkins::job::run_whitehall_data_migrations
  - govuk_jenkins::job::service_manual_rebuild_search_index
  - govuk_jenkins::job::deploy_app
  - govuk_jenkins::job::deploy_cdn
  - govuk_jenkins::job::deploy_puppet
  - govuk_jenkins::job::launch_vms
  - govuk_jenkins::job::network_config_deploy
  - govuk_jenkins::job::network_config_deploy_dryrun
  - govuk_jenkins::job::performance_platform_smokey
  - govuk_jenkins::job::smokey
  - govuk_jenkins::job::smokey_deploy
govuk_jenkins::job_builder::environment: 'production'

govuk_jenkins::ssh_key::public_key: 'AAAAB3NzaC1yc2EAAAADAQABAAABAQDvfe5R+1OKwEBQqQIECW4k4LaFrTZedFWK5pzSAM6QxpQtCbKau4ZnD1ToPLX/IGYnW9m/2QfTQoBUtJvERjJvvGs7Wy6I+nKpr4gBVuDiFWilaXZ0rhdlnfU+r/DvFwRR5qjt7pewAlzdcDKp/NAa9BPIYL+YSX4XAZE0b8YMGxeJFQ4sd4CloTJxiUF2F1t2OObXhdQfp2BKtjHMwqClxW6ZthjKcqT4tBkZfo/gzd0TG0FmykNH+tG5q9Y7oxxe52TfJudIobSLgbmXOoEuSNjlwgktb6B+K3J08txo7dG0HrDdamSDTQxXVhn1K1re3cMJokV0N59hazHh7+vx'

postgresql_api_slave_address: '10.3.4.41/32'
postgresql_slave_address: '10.3.3.13/32'
postgresql_transition_slave_address: '10.3.3.61/32'

hosts::production::carrenza_vcloud: true

hosts::production::ip_api_lb: '10.3.4.254'
hosts::production::ip_backend_lb: '10.3.3.254'
hosts::production::ip_draft_api_lb: '10.3.4.253'
hosts::production::ip_frontend_lb: '10.3.2.254'

hosts::production::api::hosts:
  api-1:
    ip: '10.3.4.16'
  api-2:
    ip: '10.3.4.17'
  api-elasticsearch-1:
    ip: '10.3.4.25'
  api-elasticsearch-2:
    ip: '10.3.4.26'
  api-elasticsearch-3:
    ip: '10.3.4.27'
  api-lb-1:
    ip: '10.3.4.101'
  api-lb-2:
    ip: '10.3.4.102'
  api-mongo-1:
    ip: '10.3.4.21'
  api-mongo-2:
    ip: '10.3.4.22'
  api-mongo-3:
    ip: '10.3.4.23'
  api-postgresql-primary-1:
    ip: '10.3.4.40'
  api-postgresql-standby-1:
    ip: '10.3.4.41'
  api-redis-1:
    ip: '10.3.4.29'
  content-store-1:
    ip: '10.3.4.11'
  content-store-2:
    ip: '10.3.4.12'
  content-store-3:
    ip: '10.3.4.13'
  draft-content-store-1:
    ip: '10.3.4.200'
  draft-content-store-2:
    ip: '10.3.4.201'
  performance-mongo-1:
    ip: '10.3.4.31'
  performance-mongo-2:
    ip: '10.3.4.32'
  performance-mongo-3:
    ip: '10.3.4.33'
  search-1:
    ip: '10.3.4.4'
  search-2:
    ip: '10.3.4.5'
  search-3:
    ip: '10.3.4.6'

hosts::production::backend::hosts:
  asset-master-1:
    ip: '10.3.3.20'
    legacy_aliases:
      - "asset-master-1.%{hiera('app_domain')}"
      - 'asset-master'
      - "asset-master.%{hiera('app_domain')}"
  asset-slave-1:
    ip: '10.3.3.21'
    legacy_aliases:
      - "asset-slave-1.%{hiera('app_domain')}"
      - 'asset-slave'
      - "asset-slave.%{hiera('app_domain')}"
  backend-1:
    ip: '10.3.3.2'
  backend-2:
    ip: '10.3.3.3'
  backend-3:
    ip: '10.3.3.4'
  backend-lb-1:
    ip: '10.3.3.101'
  backend-lb-2:
    ip: '10.3.3.102'
  elasticsearch-1:
    ip: '10.3.3.15'
  elasticsearch-2:
    ip: '10.3.3.16'
  elasticsearch-3:
    ip: '10.3.3.17'
  exception-handler-1:
    ip: '10.3.3.40'
  mapit-server-1:
    ip: '10.3.3.9'
  mapit-server-2:
    ip: '10.3.3.10'
  mongo-1:
    ip: '10.3.3.6'
    service_aliases:
      - 'mongodb'
  mongo-2:
    ip: '10.3.3.7'
  mongo-3:
    ip: '10.3.3.8'
  mysql-backup-1:
    ip: '10.3.3.93'
    legacy_aliases:
      - 'backup.mysql'
  mysql-master-1:
    ip: '10.3.3.90'
    legacy_aliases:
      - 'master.mysql'
      - "mysql.backend.%{hiera('internal_tld')}"
  mysql-slave-1:
    ip: '10.3.3.91'
    legacy_aliases:
      - 'slave.mysql'
  mysql-slave-2:
    ip: '10.3.3.92'
  performance-backend-1:
    ip: '10.3.3.80'
  performance-backend-2:
    ip: '10.3.3.81'
  postgresql-primary-1:
    ip: '10.3.3.12'
  postgresql-standby-1:
    ip: '10.3.3.13'
  rabbitmq-1:
    ip: '10.3.3.70'
  rabbitmq-2:
    ip: '10.3.3.71'
  rabbitmq-3:
    ip: '10.3.3.72'
  redis-1:
    ip: '10.3.3.50'
  redis-2:
    ip: '10.3.3.51'
  transition-postgresql-master-1:
    ip: '10.3.3.60'
    legacy_aliases:
      - 'transition-master.postgresql'
      - "transition-postgresql.backend.%{hiera('internal_tld')}"
  transition-postgresql-slave-1:
    ip: '10.3.3.61'
    legacy_aliases:
      - 'transition-slave.postgresql'
  whitehall-backend-1:
    ip: '10.3.3.25'
  whitehall-backend-2:
    ip: '10.3.3.26'
  whitehall-backend-3:
    ip: '10.3.3.27'
  whitehall-backend-4:
    ip: '10.3.3.28'
  whitehall-mysql-backup-1:
    ip: '10.3.3.34'
    legacy_aliases:
      - 'whitehall-backup.mysql'
  whitehall-mysql-master-1:
    ip: '10.3.3.30'
    legacy_aliases:
      - 'whitehall-master.mysql'
      - "whitehall-mysql.backend.%{hiera('internal_tld')}"
  whitehall-mysql-slave-1:
    ip: '10.3.3.31'
    legacy_aliases:
      - 'whitehall-slave.mysql'
  whitehall-mysql-slave-2:
    ip: '10.3.3.32'

hosts::production::frontend::hosts:
  calculators-frontend-1:
    ip: '10.3.2.11'
  calculators-frontend-2:
    ip: '10.3.2.12'
  calculators-frontend-3:
    ip: '10.3.2.13'
  frontend-1:
    ip: '10.3.2.2'
  frontend-2:
    ip: '10.3.2.3'
  frontend-3:
    ip: '10.3.2.4'
  draft-frontend-1:
    ip: '10.3.2.200'
  draft-frontend-2:
    ip: '10.3.2.201'
  performance-frontend-1:
    ip: '10.3.2.20'
  performance-frontend-2:
    ip: '10.3.2.21'
  whitehall-frontend-1:
    ip: '10.3.2.5'
  whitehall-frontend-2:
    ip: '10.3.2.6'
  whitehall-frontend-3:
    ip: '10.3.2.10'
  whitehall-frontend-4:
    ip: '10.3.2.14'
  whitehall-frontend-5:
    ip: '10.3.2.15'
  whitehall-frontend-6:
    ip: '10.3.2.16'
  whitehall-frontend-7:
    ip: '10.3.2.17'
  frontend-lb-1:
    ip: '10.3.2.101'
  frontend-lb-2:
    ip: '10.3.2.102'

hosts::production::management::hosts:
  jenkins-1:
    ip: '10.3.0.3'
  puppetmaster-1:
    ip: '10.3.0.5'
    legacy_aliases:
      - 'puppet'
    service_aliases:
      - 'puppet'
      - 'puppetdb'
  monitoring-1:
    ip: '10.3.0.20'
    legacy_aliases:
      - 'monitoring'
    service_aliases:
      - 'alert'
      - 'monitoring'
  graphite-1:
    ip: '10.3.0.22'
    legacy_aliases:
      - "graphite.%{hiera('app_domain')}"
    service_aliases:
      - 'graphite'
  logs-cdn-1:
    ip: '10.3.0.27'
  logging-1:
    ip: '10.3.0.28'
    service_aliases:
      - 'logging'
  logs-elasticsearch-1:
    ip: '10.3.0.29'
    service_aliases:
      - 'logs-elasticsearch'
  logs-elasticsearch-2:
    ip: '10.3.0.30'
  logs-elasticsearch-3:
    ip: '10.3.0.31'
  logs-redis-1:
    ip: '10.3.0.40'
  logs-redis-2:
    ip: '10.3.0.41'
  backup-1:
    ip: '10.3.0.50'
  etcd-1:
    ip: '10.3.0.60'
  etcd-2:
    ip: '10.3.0.61'
  etcd-3:
    ip: '10.3.0.62'
  jumpbox-1:
    ip: '10.3.0.100'
  mirrorer-1:
    ip: '10.3.0.128'
  jumpbox-2:
    ip: '10.3.0.200'

hosts::production::redirector::hosts:
  bouncer-1:
    ip: '10.3.5.4'
  bouncer-2:
    ip: '10.3.5.5'
  bouncer-3:
    ip: '10.3.5.6'

hosts::production::router::hosts:
  cache-1:
    ip: '10.3.1.2'
  cache-2:
    ip: '10.3.1.3'
  cache-3:
    ip: '10.3.1.4'
  draft-cache-1:
    ip: '10.3.1.200'
  draft-cache-2:
    ip: '10.3.1.201'
  router-backend-1:
    ip: '10.3.1.10'
  router-backend-2:
    ip: '10.3.1.11'
  router-backend-3:
    ip: '10.3.1.12'
  cache:
    ip: '10.3.1.254'
    legacy_aliases:
      - 'cache'
      - "www.%{hiera('app_domain')}"
      - "www-origin.%{hiera('app_domain')}"
      - "assets-origin.%{hiera('app_domain')}"
    service_aliases:
      - 'cache'
      - 'router'
  router-backend-internal-lb:
    ip: '10.3.1.253'
    legacy_aliases:
      - "router-api.%{hiera('app_domain')}"
  draft-cache-internal-lb:
    ip: '10.3.1.252'
    legacy_aliases:
      - "draft-router-api.%{hiera('app_domain')}"

postfix::rewrite_mail_list: 'machine.email.carrenza'
