---
app_domain: 'production.alphagov.co.uk'

asset_root: "https://assets-origin.%{hiera('app_domain')}"

base::supported_kernel::enabled: true

efg_domain: "www.sflg.gov.uk"

govuk::apps::errbit::errbit_email_from: 'govuk-winston+errbit-staging@digital.cabinet-office.gov.uk'
govuk::apps::govuk_crawler_worker::airbrake_env: 'staging'
govuk::apps::publicapi::backdrop_host: 'www.staging.performance.service.gov.uk'
govuk::apps::publisher::nagios_data_importer_check: false
govuk::apps::sidekiq_monitoring::enabled: true

govuk::deploy::aws_ses_smtp_host: 'email-smtp.eu-west-1.amazonaws.com'
govuk::deploy::config::errbit_environment_name: 'staging'
govuk::deploy::setup::ssh_keys:
    jenkins_key: AAAAB3NzaC1yc2EAAAABIwAAAQEAksVh+OynwACD1/gZwj+s+bmSNiYUAhGpEu+DzhKzt6hg+x8JfaC9Usi1xWOBprCWTpCGQ2b2OK7k4iVRSM4SMYNmSO9njxcYBWmRPFRhusFHmY2x4RqyHmKlo+sPoegFbD8VcTjIyCXfxBbtYJONtrixXO+AaCLf3RlOxiPbrIh4y/EIcOpldzepcg8lqtq0S979n7qWkFUYlMKmy2Wi+q9lEjTdhUo0oGg7bUPKMUdK8m7488iOB5sgvbL0VhVpH4FJZUDSdiTcXCp2TKGVVlDOoT9jsJ9ZwsPnCy2VcRJeJRE4LpV7X0n1SV94Ddel5/gc/TU0Sounx4X4U+TOVw==
    jenkins_skyscape_key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDOStrf/KtGicl/wHWqfWfAoIYUU3LIReh6xfib17DSlTQAXcrZqnoM7riwAF8ThukTrYkLVE39+v2MGTP0wSK5O3QHRJmqeLHLSCHT135/AeV0m5/SqJ2g1iBLRM8ARucFLv0eKEtQfrdIW5cB2QfeSyj3S/tyChRQYJ/4/SIOb6WHXYDuO0xKiONS0ynOWC3/WUgkmSj67EUgXGyTDVy5cJNLHsdjIrJwpTCl/R9Owxnf6G7wIEqJecpX4xWngvjUUottWmzcvqcW92HQ8TgwPyLY8R4raT8kmyjCat9uwVCwzD67+Fqf6Wlchon2vHRdX4edhUKOrroljGfsDeyd
    jenkins_skyscape_production_key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDZ41opiEUbMk1N3wNQLrsA3bwDWlf77mGiZAUyv8rDqwwUyRgdjXBIl8+/UUUromm3XzWXgeMiQkPSZMXu2U06X05BgW90Hl8lXsL24K0JRjLf6R7erMvqjpr0u5BTRxeKVSM52ckSUiucJHBiV5gTNRTUSwwXudjnlIY5HZRYNUUUtQMwfMObg6W3j+H/87gDx5RAF4JfOplK+pvHh0uGhIUrq48Euz2KJ31YsyO4FyU6z4k66MtJivkbZ/4Z9BpzzONnL1EC5saz7vaJIRGc0kT9NVGQ7b7uMkqlN/Bb/ZDzNJi8KSxJFTh8oNEAoRoMqaSufBlZa/sjqiuWniwL
    ppdeploy_data_sync_key: AAAAB3NzaC1yc2EAAAADAQABAAABAQDGee9J6aN6PyPns8aiv2pLKrKPyyflG8LrMnjbIRUzqbqg4h/TXryuKqWTjvuQpb7jbAMV4GzP/aUM94Y8E1vYUKLbyLyG+OjoxNOBHjP7OY2a8iPXq2MmXDTEXQ0DpPsEOqPpMpzgit4P7Tl9yfPDLrKS9GBmQNc7wDfFMXjGfMCL+2ymhuDw4Bn7FIxuhqBDeoABAZPXoD8f1PiwLmWd+G27d3G391CLrD7y0PuySfX9R/EnlYoZJnOWjVyFrbbf3xiKWLn8JL36qTRYRRym8G8T6OvuUER7LBdmWBoTN/HQmQ4O0NcGx3HQZwRvANCBfKVK198TiF6kXn1mtudj

govuk_jenkins::job::network_config_deploy::environment_script_parameter: 'carrenza-staging'

govuk_jenkins::job::staging::data_sync_complete::signon_domain_old: production.alphagov.co.uk
govuk_jenkins::job::staging::data_sync_complete::signon_domain_new: staging.publishing.service.gov.uk

govuk_mysql::server::expire_log_days: 1
govuk_mysql::server::innodb_file_per_table: true
govuk_mysql::server::slow_query_log: true

govuk::node::s_api_lb::api_servers:
  - "api-1.api"
  - "api-2.api"
govuk::node::s_api_lb::content_store_servers:
  - "content-store-1.api"
  - "content-store-2.api"
  - "content-store-3.api"
govuk::node::s_api_lb::draft_content_store_servers:
- "draft-content-store-1.api"
- "draft-content-store-2.api"
govuk::node::s_api_lb::search_servers:
  - "search-1.api"
  - "search-2.api"
  - "search-3.api"
govuk::node::s_backend_lb::backend_servers:
  - 'backend-1.backend'
  - 'backend-2.backend'
  - 'backend-3.backend'
govuk::node::s_backend_lb::performance_backend_servers:
  - 'performance-backend-1.backend'
  - 'performance-backend-2.backend'
govuk::node::s_backend_lb::whitehall_backend_servers:
  - 'whitehall-backend-1.backend'
  - 'whitehall-backend-2.backend'
  - 'whitehall-backend-3.backend'
  - 'whitehall-backend-4.backend'
govuk::node::s_backend_lb::mapit_servers:
  - 'mapit-server-1.backend'
  - 'mapit-server-2.backend'
govuk::node::s_backend_lb::perfplat_public_app_domain: 'staging.performance.service.gov.uk'
govuk::node::s_cache::real_ip_header: 'True-Client-Ip'
govuk::node::s_frontend_lb::calculators_frontend_servers:
  - 'calculators-frontend-1.frontend'
  - 'calculators-frontend-2.frontend'
  - 'calculators-frontend-3.frontend'
govuk::node::s_frontend_lb::draft_frontend_servers:
  - 'draft-frontend-1.frontend'
  - 'draft-frontend-2.frontend'
govuk::node::s_frontend_lb::frontend_servers:
  - 'frontend-1.frontend'
  - 'frontend-2.frontend'
  - 'frontend-3.frontend'
govuk::node::s_frontend_lb::performance_frontend_servers:
  - 'performance-frontend-1.frontend'
  - 'performance-frontend-2.frontend'
govuk::node::s_frontend_lb::performance_frontend_apps:
  - 'spotlight'
  - 'performanceplatform-big-screen-view'
govuk::node::s_frontend_lb::whitehall_frontend_servers:
  - 'whitehall-frontend-1.frontend'
  - 'whitehall-frontend-2.frontend'
  - 'whitehall-frontend-3.frontend'
  - 'whitehall-frontend-4.frontend'
  - 'whitehall-frontend-5.frontend'
  - 'whitehall-frontend-6.frontend'
  - 'whitehall-frontend-7.frontend'
govuk::node::s_graphite::enable_basic_auth: false
govuk::node::s_licensify_lb::licensify_backend_servers:
  - 'licensify-backend-1.licensify'
  - 'licensify-backend-2.licensify'
govuk::node::s_licensify_lb::licensify_frontend_servers:
  - 'licensify-frontend-1.licensify'
  - 'licensify-frontend-2.licensify'
govuk::node::s_licensify_mongo::licensify_mongo_encrypted: true
govuk::node::s_licensify_mongo::mongodb_backup_disk: '/dev/sdb1'

hosts::production::ip_bouncer: '37.26.91.5'
hosts::production::suffixed_hosts: true

icinga::nginx::enable_basic_auth: false

#Do not enable this without speaking to Brad first
licensify::apps::licensing_web_forms::enabled: false

mongodb::server::version: '2.4.9'
mongodb::server::package_name: 'mongodb-10gen'

monitoring::checks::ses::enable: true
monitoring::checks::ses::critical: 50
monitoring::checks::ses::region: eu-west-1
monitoring::checks::ses::warning: 30

# FIXME: This is the only environment in which `monitoring_domain_suffix` is not set to `app_domain`.
#        Once we've moved to a `service.gov.uk` domain and start setting staging's `app_domain` to be
#        staging, remove `monitoring_domain_suffix` and replace it with `app_domain`.
monitoring_domain_suffix: 'staging.alphagov.co.uk'

postfix::smarthost:
- 'email-smtp.us-east-1.amazonaws.com:587'
- 'ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com:587'

shell::shell_prompt_string: 'staging'

ssh::config::allow_users:
  - 'ajlanghorn'
  - 'alexmuller'
  - 'alext'
  - 'annashipman'
  - 'benilovj'
  - 'bob'
  - 'bradleyw'
  - 'danielroseman'
  - 'davidsingleton'
  - 'dcarley'
  - 'deploy'
  - 'digitalassurancetester'
  - 'eddsowden'
  - 'elliot'
  - 'govuk-backup'
  - 'heathd'
  - 'jacobashdown'
  - 'jamiec'
  - 'jennyduckett'
  - 'joshmyers'
  - 'kushalp'
  - 'mattbostock'
  - 'paulmartin'
  - 'richardboulton'
  - 'robyoung'
  - 'timothymower'
  - 'tombooth'
  - 'tommypalmer'

users::pentest_machines:
  - 'asset-master-1.backend.production'
  - 'backend-1.backend.production'
  - 'cache-1.router.production'
  - 'frontend-1.frontend.production'
  - 'jumpbox-1.management.production'
  - 'mysql-master-1.backend.production'
  - 'postgresql-primary-1.backend.production'

users::pentest_usernames:
  - digitalassurancetester

users::usernames:
  - ajlanghorn
  - alexmuller
  - alext
  - annashipman
  - benilovj
  - bob
  - bradleyw
  - danielroseman
  - davidsingleton
  - dcarley
  - eddsowden
  - elliot
  - heathd
  - jacobashdown
  - jamiec
  - jennyduckett
  - joshmyers
  - kushalp
  - mattbostock
  - paulmartin
  - richardboulton
  - robyoung
  - timothymower
  - tombooth
  - tommypalmer

website_root: "https://www-origin.%{hiera('app_domain')}"
