---

app_domain: 'draft.production.publishing.service.gov.uk'

asset_root: 'assets-origin.draft.production.publishing.service.gov.uk'

shell::shell_prompt_string: 'draft-production'

hosts::production::apt_mirror_internal: false

govuk::apps::content_store::default_ttl: '1'
govuk::apps::errbit::errbit_email_from: 'govuk-winston+errbit-production-draft@digital.cabinet-office.gov.uk'
govuk::apps::static::global_header_text: GOV.UK (Draft)
govuk::apps::authenticating_proxy::signon_uri: 'https://signon.production.alphagov.co.uk'
govuk::apps::authenticating_proxy::errbit_uri: 'https://errbit.production.alphagov.co.uk'

govuk::deploy::config::errbit_environment_name: 'draft_production'
govuk::deploy::setup::ssh_keys:
  draft_production_skyscape_jenkins: AAAAB3NzaC1yc2EAAAADAQABAAABAQDQB4mU5iDXC4zqDdg8TtZzBoeKbXJOEVN1tNRQAAjBVD3GnAIDMWf5ChJAnEdchA/32ULkLEIko171NWCJ98nfureIMX8hiG3YqYtt4ydYV0yqTKQHz7/RhvfxvKYFL6omy8RZHEjeZ6Kf8SrELPXutT4oqJDMxaLqyZY8IYxZ/U1SJjhsBm1DCUmeuHxNRlTqEYyFEzQ9fklAR8YnbMcfhP+yBA5A+66yL03gkoDvzSUic5J5OU6J5ejupUTI5AeIu4FOep5UYs8oXf7RpXTL1b+BR6YPRCf0njnMrXauASfKV7VcxvvE0D0JbwVO82Rwls02Ug8WwH5WGJBTZ4YF

govuk::node::s_api_lb::content_store_servers:
- "content-store-1.api"
- "content-store-2.api"
govuk::node::s_cache::protect_cache_servers: true
govuk::node::s_frontend_lb::frontend_servers:
  - 'frontend-1.frontend'
  - 'frontend-2.frontend'
govuk::node::s_backend_lb::backend_servers:
  - 'backend-1.backend'
  - 'backend-2.backend'

govuk::node::s_backend::apps:
  - govuk::apps::kibana

govuk::node::s_frontend::apps:
  - govuk::apps::contacts_frontend
  - govuk::apps::government_frontend
  - govuk::apps::manuals_frontend
  - govuk::apps::static

router::gor::enable_staging: false

website_root: 'https://www-origin.draft.production.publishing.service.gov.uk'
